[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = seeed_xiao_esp32c6
framework = arduino

monitor_speed = 921600
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3

; ESP32-C6 + Arduinoでは環境差が出るため、以下のようにします。
; platform = https://github.com/pioarduino/platform-espressif32.git#develop

